services:
  converte:
    build: .
    container_name: converte
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./banco_local_pei.db:/app/banco_local_pei.db
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000