name: Deploy Automático CasaOS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar o código mais recente
        uses: actions/checkout@v4

      - name: Sincronizar arquivos para a pasta do CasaOS
        run: |
          mkdir -p /DATA/AppData/Converte/converte
          # Copia o CONTEÚDO da pasta converte do GitHub direto para o destino
          rsync -av --delete ./converte/ /DATA/AppData/Converte/converte/

      - name: Fazer o Build e Subir o Contêiner
        run: |
          cd /DATA/AppData/Converte/converte
          sudo docker compose up -d --build