name: Deploy Automático CasaOS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar o código mais recente
        uses: actions/checkout@v4

      - name: Sincronizar arquivos para a pasta do CasaOS
        run: |
          mkdir -p /DATA/AppData/Converte/converte
          # Copia os arquivos ignorando o .env e o banco de dados (para não deletar os seus)
          rsync -av --delete --exclude='.git/' --exclude='.github/' --exclude='.env' --exclude='data/' ./converte/ /DATA/AppData/Converte/converte/

      - name: Fazer o Build e Subir o Contêiner
        run: |
          cd /DATA/AppData/Converte/converte
          docker compose up -d --build